# 1. 초기 생성용 (DB 이름 제외)
[connections.mysql_server]
dialect = "mysql"
username = "root"
password = "root1234"
host = "127.0.0.1"


# 2. 일반 운영용 (DB 이름 포함)

[connections.faqdb]
dialect = "mysql"
username = "root"
password = "root1234"
host = "127.0.0.1"
database = "faqdb"